[#_Transaction]
[.doc-api-reference-driver]
=== Transaction

`class`

*Package*: `com.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

// tag::methods[]
[#_Transaction_analyze_java_lang_String]
==== method ``analyze``

[source,java]
----
@CheckReturnValue
Promise<? extends AnalyzedQuery> analyze​(java.lang.String query)
                                  throws TypeDBDriverException
----

Analayze a TypeQL query in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to analyze. a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends AnalyzedQuery>`

[caption=""]
.Code examples
[source,java]
----
transaction.analyze("match $x isa person;");
----

[#_Transaction_close_]
==== method ``close``

[source,java]
----
void close()
    throws TypeDBDriverException
----

Closes the transaction. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.close()
----

[#_Transaction_commit_]
==== method ``commit``

[source,java]
----
void commit()
     throws TypeDBDriverException
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.commit()
----

[#_Transaction_getType_]
==== method ``getType``

[source,java]
----
@CheckReturnValue
Transaction.Type getType()
----

The transaction’s type (READ, WRITE, or SCHEMA) 


[caption=""]
.Returns
`Transaction.Type`

[caption=""]
.Code examples
[source,java]
----
transaction.getType();
----

[#_Transaction_isOpen_]
==== method ``isOpen``

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

Checks whether this transaction is open. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
transaction.isOpen();
----

[#_Transaction_onClose_java_util_function_Consumer_java_lang_Throwable_]
==== method ``onClose``

[source,java]
----
void onClose​(java.util.function.Consumer<java.lang.Throwable> function)
----

Registers a callback function which will be executed when this transaction is closed. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `java.util.function.Consumer<java.lang.Throwable>`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.onClose(function);
----

[#_Transaction_options_]
==== method ``options``

[source,java]
----
@CheckReturnValue
TransactionOptions options()
----

The options for the transaction

[caption=""]
.Returns
`TransactionOptions`

[#_Transaction_query_java_lang_String]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[caption=""]
.Code examples
[source,java]
----
transaction.query("define entity person;");
----

[#_Transaction_query_java_lang_String_QueryOptions]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     QueryOptions options)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `options` a| The ``QueryOptions`` to execute the query with. a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[caption=""]
.Code examples
[source,java]
----
transaction.query("define entity person;");
----

[#_Transaction_query_java_lang_String_GivenRows]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     GivenRows givenRows)
                              throws TypeDBDriverException
----

Execute a TypeQL query with input rows in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `givenRows` a| GivenRows to be used as input to the query. a| `GivenRows`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[caption=""]
.Code examples
[source,java]
----
String query = "given $n: string, $a: integer; insert $p isa person, has name == $n, has age == $a;";
 GivenRows rows = TypeDB.Concept.givenRows(
      List.of("n", "a"),
      List.of(
          List.of(TypeDB.Concept.newString("Alice"), TypeDB.Concept.newInteger(28)), // First row
          List.of(TypeDB.Concept.newString("Bob"), TypeDB.Concept.newInteger(26))    // Second row
      )
  );
 transaction.query(query, rows);
----

[#_Transaction_query_java_lang_String_java_util_List_extends_java_util_Map_java_lang_String_​java_lang_Object_]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     java.util.List<? extends java.util.Map<java.lang.String,​java.lang.Object>> givenRows)
                              throws TypeDBDriverException
----

Execute a TypeQL query with input rows in this transaction.


See also: <<#_query_java_lang_String_com_typedb_driver_api_concept_GivenRows,``query(String, GivenRows)``>>


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `givenRows` a| Used to construct the GivenRows which will be used as input to the query. Values must be Concept or a primitive supported by TypeDB.tryConvertToValue a| `java.util.List<? extends java.util.Map<java.lang.String,​java.lang.Object>>`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[#_Transaction_query_java_lang_String_java_util_List_java_lang_String_java_util_List_extends_java_util_List_java_lang_Object_]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     java.util.List<java.lang.String> givenVariables,
                                     java.util.List<? extends java.util.List<java.lang.Object>> givenRows)
                              throws TypeDBDriverException
----

Execute a TypeQL query with input rows in this transaction.


See also: <<#_query_java_lang_String_com_typedb_driver_api_concept_GivenRows,``query(String, GivenRows)``>>


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `givenVariables` a| The variables used to construct the GivenRows which will be used as input to the query. a| `java.util.List<java.lang.String>`
a| `givenRows` a| The rows used to construct the GivenRows which will be used as input to the query. Values must be Concept or a primitive supported by TypeDB.tryConvertToValue a| `java.util.List<? extends java.util.List<java.lang.Object>>`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[#_Transaction_query_java_lang_String_QueryOptions_GivenRows]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     QueryOptions options,
                                     GivenRows givenRows)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `options` a| The ``QueryOptions`` to execute the query with. a| `QueryOptions`
a| `givenRows` a| GivenRows to be used as input to the query. a| `GivenRows`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[#_Transaction_query_java_lang_String_QueryOptions_java_util_List_extends_java_util_Map_java_lang_String_​java_lang_Object_]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     QueryOptions options,
                                     java.util.List<? extends java.util.Map<java.lang.String,​java.lang.Object>> givenRows)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `options` a| The ``QueryOptions`` to execute the query with. a| `QueryOptions`
a| `givenRows` a| Used to construct the GivenRows which will be used as input to the query. Values must be Concept or a primitive supported by TypeDB.tryConvertToValue a| `java.util.List<? extends java.util.Map<java.lang.String,​java.lang.Object>>`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[#_Transaction_query_java_lang_String_QueryOptions_java_util_List_java_lang_String_java_util_List_extends_java_util_List_java_lang_Object_]
==== method ``query``

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     QueryOptions options,
                                     java.util.List<java.lang.String> givenVariables,
                                     java.util.List<? extends java.util.List<java.lang.Object>> givenRows)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `options` a| The ``QueryOptions`` to execute the query with. a| `QueryOptions`
a| `givenVariables` a| The variables used to construct the GivenRows which will be used as input to the query. a| `java.util.List<java.lang.String>`
a| `givenRows` a| The rows used to construct the GivenRows which will be used as input to the query. Values must be Concept or a primitive supported by TypeDB.tryConvertToValue a| `java.util.List<? extends java.util.List<java.lang.Object>>`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[#_Transaction_rollback_]
==== method ``rollback``

[source,java]
----
void rollback()
       throws TypeDBDriverException
----

Rolls back the uncommitted changes made via this transaction. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.rollback()
----

// end::methods[]

