[#_ITransaction]
[.doc-api-reference-driver]
=== ITransaction

`class`

*Package*: `TypeDB.Driver.Api`



A transaction with a TypeDB database.

// tag::methods[]
[#_Promise_IAnalyzedQuery_TypeDB_Driver_Api_ITransaction_Analyze_string_query_]
==== method ``Analyze``

[source,cs]
----
Promise< IAnalyzedQuery > Analyze(string query)
----



Analyzes a TypeQL query and returns information about its structure and type inference results.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to analyze. a| `string`
|===

[caption=""]
.Returns
`Promise< IAnalyzedQuery >`

[#_void_TypeDB_Driver_Api_ITransaction_Close_]
==== method ``Close``

[source,cs]
----
void Close()
----



Closes the transaction.

[caption=""]
.Returns
`void`

[#_void_TypeDB_Driver_Api_ITransaction_Commit_]
==== method ``Commit``

[source,cs]
----
void Commit()
----



Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is committed successfully, it gets closed after the commit call.

[caption=""]
.Returns
`void`

[#_bool_TypeDB_Driver_Api_ITransaction_IsOpen_]
==== method ``IsOpen``

[source,cs]
----
bool IsOpen()
----



Checks whether this transaction is open.

[caption=""]
.Returns
`bool`

[#_void_TypeDB_Driver_Api_ITransaction_OnClose_Action_Exception_function_]
==== method ``OnClose``

[source,cs]
----
void OnClose(Action< Exception? > function)
----



Registers a callback function which will be executed when this transaction is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `Action< Exception? >`
|===

[caption=""]
.Returns
`void`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query)
----



Executes a TypeQL query in this transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_QueryOptions_options_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, QueryOptions options)
----



Executes a TypeQL query in this transaction with custom options.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `options` a| Query options. a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_IGivenRows_givenRows_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, IGivenRows givenRows)
----



Executes a TypeQL query with input rows in this transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `givenRows` a| Input rows. a| `IGivenRows`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_List_Dictionary_string_object_givenRows_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, List< Dictionary< string, object? > > givenRows)
----



Executes a TypeQL query with input rows supplied as a list of dictionaries of raw values.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `givenRows` a| Rows as dictionaries from variable name to ``IConcept`` or a supported .NET primitive. a| `List< Dictionary< string, object? > >`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_List_string_givenVariables_List_List_object_givenRows_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, List< string > givenVariables, List< List< object? > > givenRows)
----



Executes a TypeQL query with input rows supplied as parallel variable and value lists of raw values.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `givenVariables` a| Variable names. a| `List< string >`
a| `givenRows` a| Row values; each entry must be ``IConcept`` or a supported .NET primitive. a| `List< List< object? > >`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_QueryOptions_options_IGivenRows_givenRows_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, QueryOptions options, IGivenRows givenRows)
----



Executes a TypeQL query with input rows in this transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `options` a| Query options. a| `QueryOptions`
a| `givenRows` a| Input rows built via ``TypeDB.Concept.GivenRows``. a| `IGivenRows`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[caption=""]
.Code examples
[source,cs]
----
string query = "given $n: string, $a: integer; insert $p isa person, has name == $n, has age == $a;"; IGivenRows rows = TypeDB.Concept.GivenRows( new List<string> { "n", "a" }, new List<List<IConcept?>> { new List<IConcept?> { TypeDB.Concept.NewString("Alice"), TypeDB.Concept.NewInteger(28) }, // First row new List<IConcept?> { TypeDB.Concept.NewString("Bob"), TypeDB.Concept.NewInteger(26) } // Second row } ); transaction.Query(query, new QueryOptions(), rows).Resolve(); TypeDB.Driver.Api.IGivenRows Definition IGivenRows.cs:22 TypeDB Definition TypeDB.cs:29
----

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_QueryOptions_options_List_Dictionary_string_object_givenRows_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, QueryOptions options, List< Dictionary< string, object? > > givenRows)
----



Executes a TypeQL query with input rows and options, rows supplied as a list of dictionaries of raw values.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `options` a| Query options. a| `QueryOptions`
a| `givenRows` a| Rows as dictionaries from variable name to ``IConcept`` or a supported .NET primitive. a| `List< Dictionary< string, object? > >`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_Promise_IQueryAnswer_TypeDB_Driver_Api_ITransaction_Query_string_query_QueryOptions_options_List_string_givenVariables_List_List_object_givenRows_]
==== method ``Query``

[source,cs]
----
Promise< IQueryAnswer > Query(string query, QueryOptions options, List< string > givenVariables, List< List< object? > > givenRows)
----



Executes a TypeQL query with input rows and options, rows supplied as parallel variable and value lists of raw values.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `options` a| Query options. a| `QueryOptions`
a| `givenVariables` a| Variable names. a| `List< string >`
a| `givenRows` a| Row values; each entry must be ``IConcept`` or a supported .NET primitive. a| `List< List< object? > >`
|===

[caption=""]
.Returns
`Promise< IQueryAnswer >`

[#_void_TypeDB_Driver_Api_ITransaction_Rollback_]
==== method ``Rollback``

[source,cs]
----
void Rollback()
----



Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
`void`

[#_TransactionType_TypeDB_Driver_Api_ITransaction_Type]
==== method ``Type``

[source,cs]
----
TransactionType TypeDB.Driver.Api.ITransaction.Type
----



The transaction's type (Read, Write, or Schema).

[caption=""]
.Returns
`TransactionType`

// end::methods[]

